@startuml

title __SRC's Class Diagram__\n

  namespace bank_system_project {
    class Account   extends Customer implements Action , Loans , AccountValidity{
        + LoanAmount : int
        + validity : String
        - accnumber : int
        - acctype : String
        - credit : int
        - debt : int
        + Account()
        + Account()
        + Loanapproval()
        + Pause_Account()
        + delete_Account()
        + deposit()
        + getAccnumber()
        + getAcctype()
        + getCredit()
        + getDebt()
        + setAccnumber()
        + setAcctype()
        + setCredit()
        + setDebt()
        + toString()
        + withdraw()
    }
  }
  

  namespace bank_system_project  {
    interface AccountValidity {
        {abstract} + Pause_Account()
        {abstract} + delete_Account()
    }
  }
  

  namespace bank_system_project {
    interface Action {
        {abstract} + deposit()
        {abstract} + withdraw()
    }
  }
  

  namespace bank_system_project  {
    class Customer extends Person{
        + address : String
        + sourceofincome : int
        + Customer()
        + Customer()
        + getAddress()
        + getSourceofincome()
        + setAddress()
        + setSourceofincome()
        + toString()
    }
  }
  

  namespace bank_system_project  {
    class Employee extends Person {
        + accesslevel : int
        + salary : int
        + Employee()
        + Employee()
        + getAccesslevel()
        + getSalary()
        + setAccesslevel()
        + setSalary()
        + toString()
    }
  }
  

  namespace bank_system_project {
    class Interest extends Account{
        + interestrate : int
        + Interest()
        + Interest()
        + setCredit()
        + toString()
    }
  }
  

  namespace bank_system_project  {
    interface Loans {
        {abstract} + Loanapproval()
    }
  }
  

  namespace bank_system_project  {
    class Main {
        {static} + main()
    }
  }
  

  namespace bank_system_project  {
    class Person {
        + DOB : String
        + ID : int
        + employment : String
        + name : String
        + Person()
        + Person()
        + getDOB()
        + getEmployment()
        + getID()
        + getName()
        + setDOB()
        + setEmployment()
        + setID()
        + setName()
        + toString()
    }
  }
  

  Account .up.|> AccountValidity
  Account .up.|> Action
  Account .up.|> Loans
  Employee.up.|> Person


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
